const NEW_PLAYLIST = [
    {
        no: 1,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi",
        views: 954,
        likes: 23,
        author: "N D T",
        genre: "Pop Ballad",
        tracks: 15,
        isPlaying: true,
    },
    {
        no: 2,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 3,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 4,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 5,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 6,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 7,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 8,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 9,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
    {
        no: 10,
        img_src: 'https://res.cloudinary.com/dbda40mpf/image/upload/v1698906954/samples/man-on-a-street.jpg',
        name_playlist: "Day la album nhac cua toi 2",
        views: 954,
        likes: 23,
        author: "N D T 2",
        genre: "Rock",
        tracks: 8,
        isPlaying: false,
    },
]

export default NEW_PLAYLIST